name: Fuma Docs

on:
  push:
    branches:
      - infra/tetsing/cicd
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "infra/tetsing/cicd"

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        server: [fumadocs]

    steps:

      - name: Checkout
        uses: actions/checkout@v3


      - name: Deploy on ${{ matrix.server }}
        run: |
          ssh ${{ matrix.server }} << 'EOF'
            cd mrscraper-docs-fumadocs
            git pull
            bash deploy.sh
          EOF
